set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR i386)

set(TRIPLE i686-elf)

set(CMAKE_C_COMPILER   ${TRIPLE}-gcc)
set(CMAKE_ASM_COMPILER ${TRIPLE}-gcc)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_OSX_SYSROOT "" CACHE PATH "" FORCE)
set(CMAKE_OSX_ARCHITECTURES "" CACHE STRING "" FORCE)
set(CMAKE_OSX_DEPLOYMENT_TARGET "" CACHE STRING "" FORCE)

set(USERSPACE_CFLAGS
    "-m32 -march=i386 -ffreestanding -fno-pic -fno-pie -no-pie -fno-stack-protector"
)

set(USERSPACE_LDFLAGS
    "-static -nostdlib -nostartfiles -Wl,--build-id=none -m32"
)

set(CMAKE_C_FLAGS_INIT "${USERSPACE_CFLAGS}")
set(CMAKE_EXE_LINKER_FLAGS_INIT "${USERSPACE_LDFLAGS}")

set(CMAKE_C_STANDARD_LIBRARIES "" CACHE STRING "" FORCE)
set(CMAKE_EXE_LINKER_FLAGS "" CACHE STRING "" FORCE)
set(CMAKE_C_FLAGS "" CACHE STRING "" FORCE)
